name: Deploy Server Config

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release. Eg: 0.31.0_1735'
        required: true
      teamSize:
        description: 'Max Team Size'
        required: true
        type: choice
        options:
          - Quads
          - Duos
          - Solos
      enableBots:
        description: 'Enable Bots Backfill'
        required: false
        type: boolean
        default: false
      botsBackfillLimit:
        description: 'Add Bots Backfill Limit'
        required: true
        default: '60'

jobs:
  update_yaml:
    permissions:
      contents: 'write'
      id-token: 'write'
    name: Yaml Updater
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Delete Config
      run: rm Agones/actionRunnerConfig.yaml

    - name: Copy File Content
      run: cp Agones/actionRunnerConfigTemplate.yaml Agones/actionRunnerConfig.yaml
      
    - name: Replace _BUILD_NUMBER_ in yaml template
      run: |
          VERSION=$(echo "${{ github.event.inputs.version }}" | rev | cut -c 1-4 | rev)
          sed -i "s/_BUILD_NUMBER_/$VERSION/g" Agones/actionRunnerConfig.yaml
      
    - name: Replace _VERSION_ in yaml template
      run: sed -i "s/_VERSION_/${{github.event.inputs.version}}/g" Agones/actionRunnerConfig.yaml

    - name: Replace _TEAM_SIZE_ in yaml template if QUADS
      if: ${{ github.event.inputs.teamSize == 'Quads' }}
      run: sed -i "s/_TEAM_SIZE_/2/g" Agones/actionRunnerConfig.yaml
      
    - name: Replace _TEAM_SIZE_ in yaml template if DUOS
      if: ${{ github.event.inputs.teamSize == 'Duos' }}
      run: sed -i "s/_TEAM_SIZE_/1/g" Agones/actionRunnerConfig.yaml

    - name: Replace _TEAM_SIZE_ in yaml template if SOLOs
      if: ${{ github.event.inputs.teamSize == 'Solos' }}
      run: sed -i "s/_TEAM_SIZE_/0/g" Agones/actionRunnerConfig.yaml

    - name: Replace _BOTS_BACKFILL_ENABLE_ in yaml template if False
      if: ${{ github.event.inputs.enableBots == 'false' }}
      run: sed -i "s/_BOTS_BACKFILL_ENABLE_/0/g" Agones/actionRunnerConfig.yaml

    - name: Replace _BOTS_BACKFILL_ENABLE_ in yaml template if True
      if: ${{ github.event.inputs.enableBots == 'true' }}
      run: sed -i "s/_BOTS_BACKFILL_ENABLE_/1/g" Agones/actionRunnerConfig.yaml

    - name: Replace _BACKFILL_SIZE_ in yaml template
      run: sed -i "s/_BACKFILL_SIZE_/${{github.event.inputs.botsBackfillLimit}}/g" Agones/actionRunnerConfig.yaml

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Agones/actionRunnerConfig.yaml
        git commit -m "Update config in actionRunnerConfig.yaml"
        git push
    - name: GCP Cloud Auth
      id: 'gcp-cloud-auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - name: GKE Auth
      id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'agones-cluster'
        location: 'asia-south1-a'
        use_auth_provider : 'true'
    - id: 'get-pods'
      run: 'kubectl get fleets'
    - name: Apply the Configuration
      run: kubectl create -f https://raw.githubusercontent.com/JuneSoftware/icc/main/Agones/actionRunnerConfig.yaml
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
